# Generated by Django 3.1.7 on 2021-03-05 22:25

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210303_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('subtitle', models.CharField(max_length=254)),
                ('embed', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
