# Generated by Django 3.1.7 on 2021-03-11 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210310_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='banner_mobile_size',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='banner_tablet_size',
        ),
    ]
