# Generated by Django 3.1.7 on 2021-03-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210311_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='banner_mobile_size',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='banner_tablet_size',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
