# Generated by Django 3.1.7 on 2021-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210311_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
