# Generated by Django 3.1.7 on 2021-03-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210323_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='banner_mobile_size',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='banner_tablet_size',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='link_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='advert',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='recorded',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='youtube_link',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
