# Generated by Django 3.1.7 on 2021-03-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=254)),
                ('title', models.CharField(max_length=254)),
                ('Content', models.CharField(blank=True, max_length=254, null=True)),
                ('primaryImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('secondaryImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
