# Generated by Django 3.1.7 on 2021-03-05 20:18

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_samplevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplevideo',
            name='embed',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
