# Generated by Django 3.1.7 on 2021-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210305_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
