# Generated by Django 3.1.7 on 2021-03-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_samplevideo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplevideo',
            name='thumbnail',
        ),
    ]
