# Generated by Django 3.1.7 on 2021-03-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='caption',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
