# Generated by Django 3.1.7 on 2021-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_images_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplevideo',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
