# Generated by Django 3.1.7 on 2021-03-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_samplevideo_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplevideo',
            name='embed',
        ),
        migrations.AddField(
            model_name='samplevideo',
            name='recorded',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
