# Generated by Django 3.1.7 on 2021-03-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
