# Generated by Django 3.1.7 on 2021-03-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_albumsongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_jacket',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='albumsongs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumsongs', to='products.album'),
        ),
        migrations.AlterField(
            model_name='albumsongs',
            name='song_title',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_link',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
