# Generated by Django 3.1.7 on 2021-03-02 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_albumsongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsongs',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumsongs', to='products.album'),
        ),
    ]
